name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun test

  build:
    name: Build
    runs-on: ubuntu-latest
    # Define the environment variable at the job level
    env:
     DATABASE_URL: ${{ secrets.DATABASE_URL }}
     DIRECT_URL: ${{ secrets.DIRECT_URL }}
      # Public Vars (Required for Next.js Bundle)
     NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
     NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
     NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: nextjs-build
          path: .next
          retention-days: 7